server:
  port: 10003

spring:
  application:
    name: dtmp-streaming

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dtmp_dev?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    name: root
    password: onlee(GuZRkCN15S5s8WOF74SY2C4G4KqkZfi2zSTm9nJ9wqs=)

  cloud:
    nacos:
      discovery:
        server-addr: 49.232.20.165:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 加密配置
jasypt:
  encryptor:
    algorithm: "PBEWithMD5AndDES"
    property:
      prefix: "onlee("
      suffix: ")"